---
# file: roles/rhua/tasks/main.yml
# tasks related to rhua setup
- name: set hostname
  hostname: name=rhua.example.com
  tags: rhua

- import_tasks: save.yml
  when: saveandrestore | default(False)
  tags: rhua,save
