---
# file: launchpad.yml
# the configuration of the launchpad and the actual launch of the installer
- hosts: LAUNCHPAD
  vars:
    installer_volumes:
      - "/home/{{ ansible_env.SUDO_USER }}/.ssh/id_ecdsa_launchpad:/ssh-keyfile:Z"
    installer_command: >
      rhui-installer
      --target-user {{ unpriv_user }}
      {% if mig | default(False) %}
      --migrate-from-rhui-4
      {% if toanotherrhua | default(False) %}
      --source-host rhua.example.com
      --target-host anotherrhua.example.com
      {% else %}
      --target-host rhua.example.com
      {% endif %}
      {% elif saveandrestore | default(False) %}
      --target-host anotherrhua.example.com
      --remote-fs-server anotherrhua.example.com:/export
      --cds-lb-hostname lb.example.com
      {% elif clone | default(False) %}
      --clone
      --source-host rhua.example.com
      --target-host anotherrhua.example.com
      --migration-fs-server anotherrhua.example.com:/export
      {% else %}
      --target-host rhua.example.com
      --remote-fs-server {{ 'none' if local_content | default(False) else 'nfs.example.com:/export' }}
      {% if not boxed | default(False) %}
      --cds-lb-hostname lb.example.com
      {% endif %}
      {% endif %}
      {% if not saveandrestore | default(False) %}
      --rhua-container-registry {{ registry['hostname'] }}
      {% endif %}
      {% if rhua_image is defined %}
      --rhua-container-image {{ rhua_image }}
      {% endif %}
      --podman-username {{ registry['username'] }}
      --podman-password {{ registry['password'] }}
    families_that_need_root_for_containers:
      - Suse
    distros_that_need_docker:
      - Amazon
  handlers:
    - import_tasks: roles/common/handlers/main.yml
  roles:
    - launchpad
