---
# file: site.yml
# top-level deployment playbook
- hosts: RHUA
  roles:
    - rhui_nodes

- hosts: all
  roles:
    - common

- import_playbook: filesystem.yml
  when: not local_content | default(False)
- import_playbook: rhua.yml
- import_playbook: anotherrhua.yml
  when: mig | default(False) and toanotherrhua | default(False) or clone | default(False) or saveandrestore | default(False)
- import_playbook: haproxy.yml
- import_playbook: cds.yml
- import_playbook: cli.yml
- import_playbook: launchpad.yml
- import_playbook: tests.yml
- import_playbook: postmig.yml
  when: mig | default(False) and not toanotherrhua | default(False)
