# file: roles/haproxy/tasks/kube.yml

- name: deploy minikube
  block:
  - name: create the bin directory for the unprivileged user
    file:
      path: /home/{{ ansible_facts['env']['SUDO_USER'] }}/bin
      state: directory
    become: False

  - name: download minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /home/{{ ansible_facts['env']['SUDO_USER'] }}/bin/minikube
      mode: "755"
    become: False

  - name: make sure podman is installed
    package:
      name: podman
      state: present

  - name: block for non-prod registries
    block:
    - name: create the directory for container certs for minikube
      file:
        name: "/home/{{ ansible_facts['env']['SUDO_USER'] }}/.minikube/certs"
        state: directory

    - name: copy the RH CA cert to this directory
      copy:
        src: /etc/rhsm/ca/redhat-uep.pem
        dest: "/home/{{ ansible_facts['env']['SUDO_USER'] }}/.minikube/certs"
        remote_src: True
    when: registry['insecure'] | default(False) | bool
    become: False

  - name: start minikube
    command:
      cmd: minikube start --driver=podman
      creates: /home/{{ ansible_facts['env']['SUDO_USER'] }}/.kube/config
    become: False
  tags: kube
